retract :-
    retract(patient(X)),
    retract(shaking_chills(X)),
    retract(high_fever(X)),
    retract(sweating(X)),
    retract(headache(X)),
    retract(coughing(X)),
    retract(nausea(X)),
    retract(vomiting(X)),
    retract(swollen_lymph_glands(X)),
    retract(muscle_pain(X)),
    retract(joint_pain(X)),
    retract(skin_rash(X)),
    retract(bleeding_nose_and_gums(X)),
    retract(bruising_skin(X)),
    retract(red_bumps(X)),
    retract(blisters(X)),
    retract(scabs(X)),
    retract(itchy_skin(X)),
    retract(open_wound(X)),
    retract(contaminated_soil_contact(X)), %for leptospirosis: water OR soil
    retract(chills(X)),
    retract(yellow_skin(X)),
    retract(abdominal_pain(X)),
    retract(diarrhea(X)),
    retract(allergies(X)),
    retract(smoking(X)),
    retract(exercised(X)),
    retract(heartburn(X)),
    retract(sinusitis(X)),
    retract(took_medication(X)),
    retract(exposed_to_smoke(X)),
    retract(shortness_of_breath(X)),
    retract(chest_pain(X)),
    retract(coughing(X)),
    retract(wheezing(X)),
    retract(sore_throat(X)),
    retract(nasal_congestion(X)),
    retract(runny_nose(X)),
    retract(fatigue(X)),
    retract(confusion(X)),
    retract(lower_body_temperature(X)),
    retract(exposed_to_measles(X)),
    retract(dry_cough(X)),
    retract(inflamed_eyes(X)),
    retract(kopliks_spots(X)),
    retract(red_eyes(X)),
    retract(stinging_eyes(X)),
    retract(itchy_eyes(X)),
    retract(blurry_vision(X)),
    retract(tearing(X)),
    retract(photophobia(X)),
    retract(discharge_from_eye(X)),
    retract(foreign_body_sensation(X)),
    retract(exposed_to_tb(X)),
    retract(weight_loss(X)),
    retract(low_appetite(X)), %same as loss_of_appetite
    retract(coughing_with_blood(X)),
    retract(night_sweats(X)),
    retract(fever(X)),
    retract(bitten_by_rabid_animal(X)),
    retract(agitation(X)),
    retract(anxiety(X)),
    retract(hyperactivity(X)),
    retract(difficulty_swallowing(X)),
    retract(excessive_salivation(X)),
    retract(fear_from_drinking_fluids(X)),
    retract(hallucinations(X)),
    retract(insomnia(X)),
    retract(partial_paralysis(X)),
    retract(rapid_dehydration(X)),
    retract(dry_tongue(X)),
    retract(thirsty(X)),
    retract(blood_pressure_falls(X)),
    retract(faint_pulse(X)),
    retract(muscular_cramps(X)),
    retract(hollow_sunken_eyes(X)),
    retract(wrinkled_skin(X)),
    retract(lethargy(X)),
    retract(seizures(X)),
    retract(red_rash_between_toes(X)),
    retract(itchy_feet(X)),
    retract(dryness(X)),
    retract(scaling(X)),
    retract(contaminated_food_contact(X)),
    retract(contaminated_water_contact(X)),
    retract(stomach_pain(X)),
    retract(hepa_b_infected_contact(X)),
    retract(light_colored_poop(X)),
    retract(belly_pain(X)),
    retract(mosquito_bite(X)).











