retract :-
    retract(patient(X)),
    retract(shaking_chills(X)),
    retract(high_fever(X)),
    retract(sweating(X)),
    retract(headache(X)).
nausea(X).
vomiting(X).
swollen_lymph_glands(X).
muscle_pain(X).
joint_pain(X).
skin_rash(X).
bleeding_nose_and_gums(X).
bruising_skin(X).
red_bumps(X).
blisters(X).
scabs(X).
itchy_skin(X).
open_wound(X).
contaminated_soil_contact(X). %for leptospirosis: water OR soil
chills(X).
yellow_skin(X).
abdominal_pain(X).
diarrhea(X).
allergies(X).
smoking(X).
exercised(X).
heartburn(X).
sinusitis(X).
took_medication(X).
exposed_to_smoke(X).
shortness_of_breath(X).
chest_pain(X).
coughing(X).
wheezing(X).
sore_throat(X).
nasal_congestion(X).
runny_nose(X).
fatigue(X).
confusion(X).
lower_body_temperature(X).
exposed_to_measles(X).
dry_cough(X).
inflamed_eyes(X).
kopliks_spots(X).
red_eyes(X).
stinging_eyes(X).
itchy_eyes(X).
blurry_vision(X).
tearing(X).
photophobia(X).
discharge_from_eye(X).
foreign_body_sensation(X).
exposed_to_tb(X).
weight_loss(X).
low_appetite(X). %same as loss_of_appetite
coughing_with_blood(X).
night_sweats(X).
fever(X).
bitten_by_rabid_animal(X).
agitation(X).
anxiety(X).
hyperactivity(X).
difficulty_swallowing(X).
excessive_salivation(X).
fear_from_drinking_fluids(X).
hallucinations(X).
insomnia(X).
partial_paralysis(X).
rapid_dehydration(X).
dry_tongue(X).
thirsty(X).
blood_pressure_falls(X).
faint_pulse(X).
muscular_cramps(X).
hollow_sunken_eyes(X).
wrinkled_skin(X).
lethargy(X).
seizures(X).
red_rash_between_toes(X).
itchy_feet(X).
dryness(X).
scaling(X).
contaminated_food_contact(X).
contaminated_water_contact(X).
stomach_pain(X).
hepa_b_infected_contact(X).
light_colored_poop(X).
belly_pain(X).
mosquito_bite(X).
