symptom(high_fever).
symptom(headache).
symptom(swollen_lymph_glands).
symptom(muscle_pain).
symptom(joint_pain).
symptom(skin_rash).
symptom(nausea).
symptom(vomiting).
symptom(bleeding_nose_and_gums).
symptom(bruising_on_skin).
symptom(red_bumps).
symptom(blisters).
symptom(scabs).
symptom(itchy_skin).
symptom(chills).
symptom(yellow_skin).
symptom(red_eyes).
symptom(diarrhea).
symptom(shortness_of_breath).
symptom(chest_pain).
symptom(coughing).
symptom(wheezing).
symptom(sore_throat).
symptom(nasal_congestion).
symptom(runny_nose).
symptom(fatigue).
symptom(confusion).
symptom(fever).
symptom(lower_body_temperature).
symptom(dry_cough).
symptom(runny_nose).
symptom(inflamed_eyes).
symptom(kopliks_spots).
symptom(stinging_eyes).
symptom(itchy_eyes).
symptom(blurry_vision).
symptom(tearing).
symptom(photophobia).
symptom(discharge_from_eye).
symptom(foreign_body_sensation).
symptom(weight_loss).
symptom(loss_of_appetite).
symptom(coughing_with_blood).
symptom(night_sweats).
symptom(headache).
symptom(agitation).
symptom(anxiety).
symptom(hyperactivity).
symptom(difficulty_swallowing).
symptom(excessive_salivation).
symptom(fear_from_drinking_fluids).
symptom(hallucinations).
symptom(insomnia).
symptom(partial_paralysis).
symptom(rapid_dehydration).
symptom(dry_tongue).
symptom(thirsty).
symptom(blood_pressure_falls).
symptom(faint_pulse).
symptom(muscular_cramps).
symptom(hollow_and_sunken_eyes).
symptom(wrinkled_skin).
symptom(lethargy).
symptom(seizures).
symptom(red_rash_between_toes).
symptom(itchy_feet).
symptom(dryness).
symptom(scaling).
symptom(low_appetite).
symptom(stomach_pain).
symptom(light_colored_poop).
